### ISSUE TITLE
pip install pgpipeline fails with FileNotFoundError: [Errno 2] No such file or directory: 'README.md'

### ISSUE THREAD

**Issue by davidthewatson** [jondot/pgpipeline#1]
Installling from pypi fails for me on MacOS Sierra 10.12.6, python 3.5.4, in a virtualenv:

```
$ pip install pgpipeline                                                                                                                                            [13:33:06]
Collecting pgpipeline
  Using cached pgpipeline-0.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/xm/pd85fv8j333d8vx8tfcv4_lm0000gn/T/pip-build-45evoxpi/pgpipeline/setup.py", line 5, in <module>
        with open('README.md') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/xm/pd85fv8j333d8vx8tfcv4_lm0000gn/T/pip-build-45evoxpi/pgpipeline/
```

However, it does work if I git clone the project and ```pip install -e``` with the relative path to the cloned repo built with ```python setup.py egg_info```.

**Comment by iamashks** [comment]
Hi @davidthewatson,

Yes, the package from pypi.org misses two files: `README.md` and `LICENSE`.

I built a package (download from here: https://gofile.io/?c=rAGoGW) including these two files, so one can just download this file and run `pip install pgpipeline-0.4.0.tar.gz` to install pgpipeline.

Thank you,
Ashutosh
